win: Compile with /bigobj
As in upstream https://crrev.com/b05c228f0b14/build/common.gypi#3234.

This is needed to build gmock_all_test on Windows (once other compile
errors are fixed):

…\crashpad\third_party\gtest\gtest\googlemock\test\gmock-matchers_test.cc
: fatal error C1128: number of sections exceeded object file format
limit : compile with /bigobj

R=scottmg@chromium.org

Review URL: https://codereview.chromium.org/1438773002 .