[icu] Fix implicit int conversion error
For some reason, this error is seen on the clang canary builders:

```
error: implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
  CBU8_NEXT(src, *char_index, src_len, code_point);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: expanded from macro 'CBU8_NEXT'
                (__t2=(s)[(i)+1]-0x80)<=0x3f) { \
                     ~~~~~~~~~~~^~~~~
```

Fix it instead of spending time bisecting for what commit might've
caused it. This should help fix the canary builders.

TEST=Checked locally that the error doesn't show up.

Change-Id: I6fc65f4dfbcd5e21f09d37c3dbb106ed7440f567
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/mini_chromium/+/2441530
Reviewed-by: Scott Graham <scottmg@chromium.org>